extends: substitution
message: "Use '%s' rather than '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#operating-environment
ignorecase: true
level: error
action:
  name: replace
source: Red Hat
swap:
  Operating Environment: operating environment
