---
#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

# GitHub Actions configuration file to
# 1. Build the project with Antora
# 2. Prepare the preview publication
# 3. Validate the internal and external links

name: Preview build
on:
  - pull_request
jobs:
  preview-build:
    name: Preview build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0 # enable git diff and building many branches
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Antora
        run: npm i antora @antora/lunr-extension
      - name: Get yearweek for cache
        id: get-date # used below
        run: echo "yearweek=$(/bin/date -u "+%Y%U")" >> $GITHUB_OUTPUT
        shell: bash
      - name: Restore cache
        uses: actions/cache@v4
        env:
          cache-name: cache
        with:
          path: .cache
          key: ${{ steps.get-date.outputs.yearweek }}
      - name: Install Vale and validate
        run: |
          sudo gem install asciidoctor
          curl -s https://api.github.com/repos/errata-ai/vale/releases/latest | grep "browser_download_url.*Linux_64-bit.tar.gz" | cut -d : -f 2,3 | tr -d \" | wget -qi -
          mkdir bin && tar -xvzf *Linux_64-bit.tar.gz -C bin
          export PATH=./bin:"$PATH"
          vale -v
          tools/validate-language-changes.sh
      - name: Generate Site
        run: npx antora antora-playbook.yml
      - name: Store pull request details for preview-publish
        run: |
          echo "${{ github.event.number }}" > PR_NUMBER
          echo "${{ github.event.pull_request.head.sha }}" > PR_SHA
      - name: Upload preview-build artifact
        uses: actions/upload-artifact@v4
        with:
          name: preview-build
          path: |
            build
            PR_NUMBER
            PR_SHA
          retention-days: 7
      - uses: actions/cache@v2
        with:
          path: tmp/.htmltest
          key: ${{ runner.os }}-htmltest
      - name: Validate internal and external links
        run: |
          curl https://htmltest.wjdp.uk | bash
          bin/htmltest
