---
#
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
name: Linting with Vale on pull request
on:
  workflow_run:
    workflows:
      - Preview build
    types:
      - completed
jobs:
  vale:
    name: Linting with Vale on pull request
    runs-on: ubuntu-latest
    steps:
      - name: Download preview-build artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: preview-build
      - name: Set variables
        id: vars
        run: echo "::set-output name=pr_sha::$(<PR_SHA)"
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: ${{ steps.vars.outputs.pr_sha }}
      - name: Vale Linter
        uses: errata-ai/vale-action@v1.5.0
        with:
          files: __onlyModified
          onlyAnnotateModifiedLines: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          OVERRIDE_GITHUB_SHA: ${{ steps.vars.outputs.pr_sha }}
