extends: substitution
message: "Use '%s' instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#comma-separated-values
ignorecase: true
level: error
action:
  name: replace
source: Red Hat
swap:
    comma-delimited values|comma delimited values|comma separated values : comma-separated values
